### PR TITLE
Fixing overriding _bundleURL on RN 0.18

### PR DESCRIPTION
**Pull request by skevy**
In RN 0.18 - _bundleURL became a private property. Import the "Private" category here to allow writing to it.

### CODE REVIEW

**Comment by lostintangent** [comment]
Thanks @skevy! I was planning to make this change this exact change this afternoon as a response to the bug you referenced. The change looks great to me :+1:

**Comment by lostintangent** [comment]
Hey @skevy, what do you think about the #141 that @joenoon submitted? Your solution is the cleanest approach, but I'd like to maintain backwards compat for now, and the KVC solution allows for that.

**Comment by skevy** [comment]
@lostintangent I think that's fine. Probably better. When we get a few versions down the line, we can use `RCTBridge+Private`.

**Comment by lostintangent** [comment]
Awesome. Thanks @skevy!

**Pull request closed without merging**
