### PR TITLE
Allow generateBundleResourceHash to be disabled for release

### PR DESCRIPTION
**Pull request by slam**
The logic that was copied from react-native was buggy. The fix to
react-native is here:

https://github.com/facebook/react-native/pull/18892

Basically just apply the same fix, otherwise setting "bundleInRelease"
in a react-native project would fail in the generateBundleResourceHash
step.

### CODE REVIEW

**Comment by alexandergoncharov** [comment]
Hi @slam ,
Thanks for contributing!

Could you please merge the current Master into your branch? It will start the tests.

**Comment by Krasavinigor** [comment]
Hello @slam!
Could please provide more information (and/or): 
* steps for reproducing the issue
* test project with the issue (optional)

Thank you!

**Comment by Krasavinigor** [comment]
I'm going to close this PR for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it.

**Comment by slam** [comment]
Sorry I missed the email until now. It went to a folder that I hadn't checked for a while.

I merged `master` into my branch just now. However, I don't have permissions to reopen this PR.

Could you reopen it? @Krasavinigor or @alexandergoncharov

**Comment by Krasavinigor** [comment]
@slam 
Unfortunately, I couldn't reproduce an issue, which will be fixed by this PR. Could you please check this: https://github.com/microsoft/react-native-code-push/pull/1695#issuecomment-638869069

Thank you!

**Comment by alexandergoncharov** [comment]
Hi @slam ,

Just a friendly ping about reprosteps for issue that you fixing. We would like to reproduce it and ensure that this PR fixes it.

**Comment by slam** [comment]
> Hi @slam ,
> 
> Just a friendly ping about reprosteps for issue that you fixing. We would like to reproduce it and ensure that this PR fixes it.

I tried to repro with the latest code push and couldn't. I think we can close this for now.

**Comment by alexandergoncharov** [comment]
@slam , oh, I see. Thanks for sharing this and contributing! I'm closing this PR for now.

**Pull request closed without merging**
