### PR TITLE
fix: fix codepush.gradle trying to access non-existent directories

### PR DESCRIPTION
**Pull request by AmyrAhmady**
This PR fixes common android issue when there's no directory such as `android/app/build/generated/res/react/release`, either `release` directory or its parent `react`
There have been multiple issues pointing to this but for some reason no one created a PR for it

this workaround or fix is taken from this comment: 
https://github.com/microsoft/react-native-code-push/issues/1578#issuecomment-503993512

### Some of the related issues:
#1977
#1578 
#1866
#1812
#1977

### CODE REVIEW

**Review by mirceanis — APPROVED** [review]
Looks great, this should be merged

**Comment by sleaper** [comment]
Will this ever be merged?

**Comment by capaj** [comment]
can anyone merge this or tell us why it is not a good idea and close it?

**Review by lucen-ms — APPROVED** [review]

**Comment by velimir-jankovic** [comment]
@AmyrAhmady thanks for the contribution! Can you please resolve conflicts? I want to merge this afterwards.

**Comment by AmyrAhmady** [comment]
@velimir-jankovic Done.

**Pull request merged**
