### PR TITLE
[iOS][Build] Add `Headers` and `Copy Files` build phases

### PR DESCRIPTION
**Pull request by sergey-akhalkov**
Due to changes in new release of `react-native@0.40.0` there is `CodePush.h file not found` error occures.
To fix it I've added `CodePush.h` header file in `Headers` build phase and changed
`codePushHeaderImportStatement` variable value from `#import "CodePush.h"`
to `#import <CodePush/CodePush.h>` in `postlink.js` file.
Fix https://github.com/Microsoft/react-native-code-push/issues/662

### CODE REVIEW

**Comment by panarasi** [comment]
@sergey-akhalkov @BretJohnson Should this not have a phase to `Copy Headers` too ? I tried running it, the headers were included, but header was not copied over to `/Users/mYName/Library/Developer/Xcode/DerivedData/MYPROJ/Build/Products/Debug-iphonesimulator/include/CodePush/CodePush.a`

**Comment by jy1989** [comment]
hi I've tried to get your modified sources and replace in my project. but the error still there. is it need to do some setup in my project?

**Comment by sergey-akhalkov** [comment]
@panarasi, @jy1989 - hi!
I've updated PR and tested it with newly created React Native apps having react-native versions `v0.39.2` and `v0.41.0-rc.0` and now it should work, please verify.

**Comment by grabbou** [comment]
Is this needed? I think the issue is that in new React Native link incorrectly fails to add path to header search path. When that gets fixed, all should work. No need to change the Codepush imports.

**Comment by buptkang** [comment]
I test this PR with @silhouettes, and it works well.

**Pull request merged**
