### PR TITLE
default JWT should be 3.0.0-beta.12 not 3.0.0-beta.7 

### PR DESCRIPTION
**Pull request by pengcao1**
when we upgrade react-native to 0.61.2 or above

### CODE REVIEW

**Comment by builtbyproxy** [comment]
Why?

**Comment by pengcao1** [comment]
> Why?

because of react-native  0.61.x or above default JWT is `3.0.0-beta.12` not `3.0.0-beta.7`,
they are conflict

**Comment by pengcao1** [comment]
any update??

**Comment by builtbyproxy** [comment]
I dont have any control over this sorry @pengcao1

**Comment by alexandergoncharov** [comment]
Hi @pengcao1 ,
Thanks for contributing!

Could you please merge the current Master into your branch? It will start the tests.

**Comment by pengcao1** [comment]
> Hi @pengcao1 ,
> Thanks for contributing!
> 
> Could you please merge the current Master into your branch? It will start the tests.

Well, Actually, I have done this action in my side, more than half year ago,
And also, I have forked the code, and merged this patch to my private repository. It's used for production for more than a half year.

**Comment by alexandergoncharov** [comment]
@pengcao1 That's cool! Thanks! And sorry for this big delay.
But could you please merge the current Master into your branch? It will start the test because we would like that we run tests for all PRs.

**Pull request merged**
