### PR TITLE
RN0.43 capacity

### PR DESCRIPTION
**Pull request by nihgwu**

### CODE REVIEW

**Comment by chirag04** [comment]
related: https://github.com/Microsoft/react-native-code-push/issues/703

@nihgwu do you also need to `add missing import import com.facebook.react.uimanager.ViewManager; in codepush.java`?

**Comment by chirag04** [comment]
this is a blocker for us. cc @sergey-akhalkov

**Comment by nihgwu** [comment]
It's already there:
https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java#L8

**Comment by chirag04** [comment]
this is weird. maybe i accidentally removed it while making it work for RN 43 and added it back.

**Comment by ptomasroos** [comment]
Blocking here as well since we're using master.

**Comment by silhouettes** [comment]
Hi @sergey-akhalkov - could you or Max reproduce this issue, and then test the fix against 0.43, 0.41 and 0.39 (just looking at the [breaking changes table](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms)) to ensure that it's backwards compatible? I assume it only applies to Android. Thank you :)

**Comment by sergey-akhalkov** [comment]
Hi @silhouettes, I've reproduced the issue for `RN 0.43.0-rc.1` for Android only and I can confirm that provided fix works well for this version of RN. I also can confirm that the fix has no backwards compatibility both with `RN 0.39` and `RN 0.41`.

**Comment by nihgwu** [comment]
@sergey-akhalkov yes I just make it work for RN0.43
you can modify it or cut a new version for backward compatibility

**Comment by aslakagens** [comment]
When will this be merged?

**Comment by rodrigopivi** [comment]
expecting this to get merged soon, it´s breaking for RN 0.43, which is already at pre release state

**Comment by silhouettes** [comment]
@aslakagens, it should be merged and also published on npm tomorrow or the day after

**Comment by sergey-akhalkov** [comment]
Merging this due to all seems to be ok, accept [this issue](https://github.com/facebook/react-native/issues/13078), that have place due to the React version 16.0.0-alpha.5 has been published on NPM. It can be fixed by downgrading React version to `16.0.0-alpha.3` in your `package.json` file and re-installing the dependencies.

**Comment by nihgwu** [comment]
@sergey-akhalkov I think that issue should have been resolved by this commit https://github.com/facebook/react-native/commit/14c31d93da30842be45c1d10879c09d744c29381

**Comment by sergey-akhalkov** [comment]
@nihgwu, thank you for clarification, the commit has been merged so I suppose the next release of RN will fix the issue.

**Comment by silhouettes** [comment]
We will publish this on npm the same day that RN 0.43 exits RC.

**Comment by michaelduminy** [comment]
@silhouettes 0.43 has been released and the problem persists. Please can you publish the new version of this lib to npm?

**Comment by sergey-akhalkov** [comment]
@michaelduminy, we've released new version of React Native Module for CodePush: `react-native-code-push@2.0.1-beta` (it's available via npm), please let me know if you see any issues or have any questions.

**Comment by michaelduminy** [comment]
Thanks @sergey-akhalkov & @silhouettes! That has solved my compilation issue 👍

**Comment by gitfdy** [comment]
Execution failed for task ':react-native-code-push:compileReleaseJavaWithJavac'.

**Comment by gitfdy** [comment]
"react-native": "^0.41.2",
 "react-native-code-push": "^4.1.0-beta",

@sergey-akhalkov  build android 

Execution failed for task ':react-native-code-push:compileReleaseJavaWithJavac'.

**Comment by max-mironov** [comment]
Hey there @gitfdy, please verify our compatibility table [here](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms). Seems that 0.41.2 is not compatible with CPRN 4.1.0-beta

**Pull request merged**
