### PR TITLE
check expectedContentLength greater than zero before assert

### PR DESCRIPTION
**Pull request by rikuayanokozy**

### CODE REVIEW

**Comment by rikuayanokozy** [comment]
@msftclas CLA now signed.

**Comment by geof90** [comment]
Will it still make sense to call the progressCallback if the expectedContentLength is -1? https://github.com/Microsoft/react-native-code-push/pull/292/files#diff-08a74f0be1f1eaa02fa1d96998fbcc5fR74

**Comment by geof90** [comment]
LGTM! I'll merge this one @lostintangent signs off.

**Comment by lostintangent** [comment]
LGTM!

**Pull request merged**
