### PR TITLE
Fix Android rollbacks when app started on background

### PR DESCRIPTION
**Pull request by aamagda**
Fixes for this issue https://github.com/microsoft/react-native-code-push/issues/2305

### CODE REVIEW

**Comment by aamagda** [comment]
@chrisglein @jedashford
Hi, guys! Could you help with tagging repo maintainers?

**Comment by ddikodroid** [comment]
@chrisglein @jedashford @andreidubov @alexandergoncharov-zz
could you review and merge this PR?

**Comment by aamagda** [comment]
up

**Comment by aamagda** [comment]
@thewulf7 @appcenter-fte 👋
Could you review this PR, please. It's still actual.

**Comment by MikhailSuendukov** [comment]
Hello @aamagda , we looked at your pull request, I have concerns that in this case the case will not be processed when a rollback needs to be performed due to an unsuccessful update download or invalid jsbundle. Which actually checks by calling `notifyAppReady` when the application is rendered. What will happen in this case? I think this case needs to be handled too.

**Comment by shehabeldeenibrahim** [comment]
@aamagda Any updates regarding this PR? I'm facing the same issue

**Comment by velimir-jankovic** [comment]
Closing due to contributor not responding. 
Feel free to re-open when responding.

**Pull request closed without merging**
