### PR TITLE
Update setup-ios.md

### PR DESCRIPTION
**Pull request by ukcasso**
The file name has changed since react-native 0.68.0. `AppDelegate.m` -> `AppDelegate.mm`

### CODE REVIEW

**Review by DmitriyKirakosyan — APPROVED** [review]

**Comment by DmitriyKirakosyan** [comment]
@ukcasso , there are other mentions of `AppDelegate.m` in the file. I think we need to change all.

And thank you for the contribution :)

**Comment by DmitriyKirakosyan** [comment]
Also, let's update the README.md file as well.

**Comment by jinuk-rarajob** [comment]
@DmitriyKirakosyan thanks for comment, okay! I'll prepare and upload again!

**Comment by ukcasso** [comment]
@DmitriyKirakosyan thanks for comment, okay! I'll prepare and upload again!

**Comment by ukcasso** [comment]
@DmitriyKirakosyan i changed everything as you said. thanks.
https://github.com/microsoft/react-native-code-push/pull/2496

**Review by bmaluff — APPROVED** [review]

**Comment by velimir-jankovic** [comment]
Closing as duplicate https://github.com/microsoft/react-native-code-push/pull/2496

**Pull request closed without merging**
