### PR TITLE
Avoid to set refs on stateless components

### LINKED ISSUE #865: CodePush should avoid set ref if stateless component wrapped
```js
function App() {
  return (
    ...
  )
}

App = codePush(App);
```

```js
05-30 22:01:52.201  1486  1720 W ReactNativeJS: Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.
05-30 22:01:52.201  1486  1720 W ReactNativeJS: 
05-30 22:01:52.201  1486  1720 W ReactNativeJS: Check the render method of `CodePushComponent`.
05-30 22:01:52.201  1486  1720 W ReactNativeJS:     in App (created by CodePushComponent)
05-30 22:01:52.201  1486  1720 W ReactNativeJS:     in CodePushComponent
05-30 22:01:52.201  1486  1720 W ReactNativeJS:     in RCTView (created by View)
05-30 22:01:52.201  1486  1720 W ReactNativeJS:     in View (created by AppContainer)
05-30 22:01:52.201  1486  1720 W ReactNativeJS:     in RCTView (created by View)
05-30 22:01:52.201  1486  1720 W ReactNativeJS:     in View (created by AppContainer)
05-30 22:01:52.201  1486  1720 W ReactNativeJS:     in AppContainer
```

### PR DESCRIPTION
**Pull request by farwayer**
fix #865 #750

### CODE REVIEW

**Comment by farwayer** [comment]
Ask for what? `ref` used internally only to make `codePushStatusDidChange` and `codePushDownloadDidProgress` functions work. With stateless components it is senselessly.

**Comment by chirag04** [comment]
Set the ref only if withRef option is provided and check if ref exists before using it in any function

**Comment by max-mironov** [comment]
Hi @farwayer , thank you so much for contribution, your PR looks good for me, I've also tested it one more time and haven't found any issues with this.

@chirag04 - could you please explain a little bit more your point - what are the benefits here with adding `withRef` option in such particular case?

**Comment by max-mironov** [comment]
Guys - I believe we can merge this changes to Master and we can always enhance this in future if needed. Please feel free to voice your concerns or suggestions if any.

**Pull request merged**
