### PR TITLE
Replace DevInternalSettings with DeveloperSettings for react-native 0.73.0

### PR DESCRIPTION
**Pull request by DmitriyKirakosyan**
`DevInternalSettings` was enclosed in ReactNative 0.73.0-rc.2, so we need to replace it with public class `DeveloperSettings`.

#2601
[AB#103487](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/103487)

### CODE REVIEW

**Review by velimirj — APPROVED** [review]

**Review by lucen-ms — DISMISSED** [review]

**Comment by serybva** [comment]
Hey guys, any plans to merge this soon? @lucen-ms @velimirj

**Review by velimir-jankovic — DISMISSED** [review]

**Comment by larsmunkholm** [comment]
I need this

**Review by Dallas62 — APPROVED** [review]

**Comment by agusvazquez** [comment]
Can we merge this? Right now 0.73 is broken. I made it work using a patch.

**Comment by yevhenlv** [comment]
Can't update RN version.... hope for faster result)

**Comment by lernerb** [comment]
Also bumping for visibility to @AnatolyPristensky 👍

**Comment by agusvazquez** [comment]
For all facing this issue, you can use this tool as a temporal fix until this is merged and released.

https://www.npmjs.com/package/patch-package

**Comment by caiodeambrosio** [comment]
need this

**Review by huextrat — APPROVED** [review]

**Comment by aderiushev** [comment]
need this!

**Comment by mchtkuk** [comment]
need this

**Comment by olegklimakov** [comment]
Hi. Any plans to release this change?

**Comment by caiodeambrosio** [comment]
Release please 🙏🏽😬

**Comment by AnatolyPristensky** [comment]
@caiodeambrosio, release 8.2.0 is available.

**Comment by larsmunkholm** [comment]
> @caiodeambrosio, release 8.2.0 is available.

There's a bug, so maybe wait

**Pull request merged**
