### PR TITLE
MOD: Note on React Native 0.14 change the API of react-native bundle,…

### PR DESCRIPTION
**Pull request by shawnXiao**
… --out has been renamed for --bundle-output

### CODE REVIEW

**Comment by lostintangent** [comment]
Hey @shawnXiao, `--out` was the pre-RN 0.14.0 name for this parameter. As of RN 0.14.0 (which is the minimum version the CodePush supports), this parameter is named `--bundle-output`. 

Which version of React Native are you using? Are you seeing the parameter show up as `--out`?

**Comment by shawnXiao** [comment]
https://facebook.github.io/react-native/docs/running-on-device-ios.html

> Note that on 0.14 we'll change the API of react-native bundle. The major changes are:

>API is now entry-file <path> based instead of url based.
>Need to specify which platform you're bundling for --platform <ios|android>.
>Option --out has been renamed for --bundle-output.
>Source maps are no longer automatically generated. Need to specify --sourcemap-output <path>

**Comment by lostintangent** [comment]
Those release notes are saying that the `--out` option was renamed to `--bundle-output`. The "for" should have been a "to" to be clearer.

**Comment by lostintangent** [comment]
I'm going to close this PR since as mentioned, the current docs reflect the current parameter names for the RN bundle command. 

If you're using RN 0.14.0 and actually having an issue following our docs, then please re-submit this PR.

**Pull request closed without merging**
