### PR TITLE
Use 3-argument RCTPromiseRejectBlock

### PR DESCRIPTION
**Pull request by jedlau**
Addresses https://github.com/Microsoft/react-native-code-push/issues/161.

### CODE REVIEW

**Comment by lostintangent** [comment]
Thanks @jedlau! This is the perfect solution. The only reason I'm somewhat waiting to merge this in is because I would ideally love to have a solution that was backwards compatible with previous React Native versions. I'm not aware of a way to do this, so I posted the [question](https://github.com/facebook/react-native/issues/5524) on the RN repro to get some advice, and maybe even propose reverting the change in the first place.

**Comment by ecjs** [comment]
Seeing how RN 0.19 was released, it would be awesome to see this merged.  Thanks for the great work on this, loving it so far.

**Comment by lostintangent** [comment]
I've been waiting to merge it because we're planning to release an update tomorrow to NPM that addresses some bugs/etc., and I don't want that release to require RN 0.19.0. Additionally, I've been petitioning that this breaking change be reverted in RN, since it's a huge shame to start requiring RN 0.19 for our users moving forward. It's looking unlikely that that will happen, so we'll likely merge this change in sometime tomorrow and release a patch update to address RN 0.19.0.

Sorry for the delay!

**Comment by ecjs** [comment]
No problem, sounds good!

**Comment by geof90** [comment]
Hi @jedlau, I will close this because I have incorporated the required changes in https://github.com/Microsoft/react-native-code-push/pull/172.

**Pull request closed without merging**
