### PR TITLE
Update Readme: codepush.gradle should be build.gradle

### PR DESCRIPTION
**Pull request by dejakob**

### CODE REVIEW

**Comment by geof90** [comment]
Hi @dejakob, codepush.gradle is the correct file. The docs in master apply to a version of the plugin that is not released yet, so it might be confusing that the latest version from NPM doesnt contain the codepush.gradle file.

**Comment by dejakob** [comment]
Oh, I see. So, I should be using the build.gradle file in the latest release?

**Comment by geof90** [comment]
You can just ignore and skip step 3 of https://github.com/microsoft/react-native-code-push#plugin-installation-android. So, no need to use any of our gradle files.

**Comment by dejakob** [comment]
Ok, thank you :)

**Pull request closed without merging**
