### PR TITLE
Add react-native@0.60 and above support

### PR DESCRIPTION
**Pull request by alexandergoncharov**
* Add `react-native.config.js`
* Update docs for setup new react-native versions
* Continue keeping `rnpm` section in `package.json` for back-compatibility with React Native version < 0.59

### CODE REVIEW

**Comment by RodolfoGS** [comment]
What is the reason to use `react-native.config.js`? I'm not using that and works.

**Comment by joseph-d-p** [comment]
What happened to the link hooks? You may want to leave a comment or close my PR #1678.

**Comment by joseph-d-p** [comment]
@RodolfoGS it is used for [migration from rnpm](https://github.com/react-native-community/cli/blob/master/docs/configuration.md#libraries). RNPM is deprecated.

**Comment by joseph-d-p** [comment]
@alexandergoncharov link hooks not anymore needed? You may close #1678 in favour of this PR.

**Comment by builtbyproxy** [comment]
😍 @alexandergoncharov thanks for this, did you miss #1645
The docs are amazing! Any preference or input on the different configs?

**Comment by MatthewPattell** [comment]
@alexandergoncharov how to use configuration with public key?

On RN 0.59, it looks like this:
```java
packages.add(new CodePush(BuildConfig.CODEPUSH_KEY_ANDROID, getApplicationContext(), isDebug(), R.string.CODEPUSH_PUBLIC_KEY));
```

**Comment by giacomocerquone** [comment]
@MatthewPattell please, this is a PR! If you need help for something open an Issue.

PS: when you execute `react-native link react-native-code-push` it adds that line for you automatically. But I do always advice to set the key in the js code. For more info see this article of mine :) https://giacomocerquone.com/blog/microsoft-codepush-integration-in-react-native-0.60

**Comment by giacomocerquone** [comment]
@alexandergoncharov hi, thanks for the work you're doing.
One quick question, considering that putting the deployment key in the native side is a facultative step, would you consider adding in the new docs a simple reminder of the possibility to put it in the js side of things (inside the codepush HoC)

**Comment by MatthewPattell** [comment]
> @MatthewPattell please, this is a PR! If you need help for something open an Issue.
> 
> PS: when you execute `react-native link react-native-code-push` it adds that line for you automatically asking you for the deployment key. But I do always advice to set the key in the js code. For more info see this article of mine :) https://giacomocerquone.com/blog/microsoft-codepush-integration-in-react-native-0.60

Look carefully at the question! I asked about the **public key**, not **deployment**

**Comment by zanechua** [comment]
Does this PR work with multi-deployment? From what I am looking at the moment with the code changes. It doesn't seem to support multi deployment for android or am i mistaken?

The following docs changed that I requested a month and a half back at https://github.com/MicrosoftDocs/appcenter-docs/pull/767 does resolve this though.

**Comment by alexandergoncharov** [comment]
Hi @zanechua ,
Thanks for this comment. Good catch!

Your approach is really good. Could you please create PR to current branch with your changes about multi-testing deployment? It will be cool to have this changes in current PR.

**Comment by alexandergoncharov** [comment]
Hi @joseph-d-p,

Unfortunatelly hooks doesn't work anymore and users have to change some part of code manually.
Here is more info: https://github.com/react-native-community/cli/issues/429
Fortunately, some steps already will be done by `autolinker`.

**Comment by zanechua** [comment]
@alexandergoncharov Created the pull request to the `migrate-to-autolink` branch with the multi-deployment docs change for android.

https://github.com/microsoft/react-native-code-push/pull/1738

**Comment by alexandergoncharov** [comment]
Hi @MatthewPattell ,

Good catch! Thanks!
Since it isn't possible to use a custom constructor with `autolinker`, we will change the constructor logic by automatically getting the `public key` from the strings and enabling code signing. The same situation with `serverUrl` field To do this we will open separate PR.

**Comment by alexandergoncharov** [comment]
Hi @giacomocerquone,

Thanks for this suggestion!
Added this note in Android and Ios setup docs.

**Comment by JeremyBradshaw7** [comment]
I'm still confused about the Android setup for RN 0.61. Is it enough to follow ONLY the section:
**Plugin Installation and Configuration for React Native 0.60 version and above**

Or do you also have to do the lower section:
**Plugin Configuration (Android)
   For React Native >= v0.29**
and
**Code Signing setup**

**Comment by builtbyproxy** [comment]
@alexandergoncharov 
This is huge thanks a lot!!
Could you please ensure it is also published to NPM: https://www.npmjs.com/package/react-native-code-push

**Comment by alexandergoncharov** [comment]
Hi @builtbyproxy ,

Thank you!
We will publish new version in npm as soon as we fix issues with custom variables(`publicKey` and `serverUrl`).

**Comment by alexandergoncharov** [comment]
Hi @JeremyBradshaw7,

Yeah, **Plugin Installation and Configuration for React Native 0.60 version and above** is enough for setup CodePush for new react-native version. **Code Signing Setup** is optional. But I got your confusing. We prepared new PR for adding more context about react-native versions in titles. 
https://github.com/microsoft/react-native-code-push/pull/1739
Could you please review it?

**Comment by builtbyproxy** [comment]
Do you need any help/testing from us around the custom variables? 
Thanks for that documentation clarification for `<= 0.59 RN`

**Comment by alexandergoncharov** [comment]
@builtbyproxy , Yeah, we just opened new PR with getting custom properties from string resources: https://github.com/microsoft/react-native-code-push/pull/1740
It would be great if you review and test it.
Please feel free to ask any questions.

Thanks for help!

**Comment by jm555jm** [comment]
@alexandergoncharov 
react-native-code-push@6.0.0

Hi, I setup by **Plugin Installation and Configuration for React Native 0.60 version and above**

and remove the following code from settings.gradle (Should add lower than 0.60)
```
include ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
```
and remove  the following code from build.gradle(app) (Should add lower than 0.60)

```
implementation project(':react-native-code-push')
```

but I could not import 
com.microsoft.codepush.react.CodePush
in MainApplication.java

And I checked the example demo, the code above still not removed
[settings.gradle](https://github.com/microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/android/settings.gradle)

Thank you

**Pull request merged**
