### PR TITLE
add serverurl codepush constructor

### PR DESCRIPTION
**Pull request by lisong**
please

### CODE REVIEW

**Comment by scottbommarito** [comment]
Thanks for submitting this change! [I've actually already made this change in another PR that's in review.](https://github.com/Microsoft/react-native-code-push/pull/357/files#diff-7a4664ad8b157a07a7a6cf0a7de26861R118) It should be merged fairly soon. Stay tuned!

**Comment by lisong** [comment]
ok

**Comment by scottbommarito** [comment]
Hey @lisong, the change you requested is now merged!

**Comment by lisong** [comment]
thanks a lot

**Pull request closed without merging**
