### PR TITLE
Move DevSettingsActivity from main to debug

### PR DESCRIPTION
**Pull request by floydkim**
closes: https://github.com/microsoft/react-native-code-push/issues/2353

### Tests
- [x] `npm run test:android`
- [x] building app, installing code-push bundle
  - on production Android app (RN 0.67.5, with same modification on react-native-code-push@7.0.4 package using patch-package)
- [x] `DevSettingsActivity` not found in `manifest-merger-release-report.txt`

---

<details>
<summary>
For anyone looking for a patch for this issue, here it is.
</summary>

```diff
diff --git a/node_modules/react-native-code-push/android/app/src/debug/AndroidManifest.xml b/node_modules/react-native-code-push/android/app/src/debug/AndroidManifest.xml
new file mode 100644
index 0000000..5bd1596
--- /dev/null
+++ b/node_modules/react-native-code-push/android/app/src/debug/AndroidManifest.xml
@@ -0,0 +1,10 @@
+<manifest xmlns:android="http://schemas.android.com/apk/res/android"
+    package="com.microsoft.codepush.react">
+
+    <uses-permission android:name="android.permission.INTERNET" />
+
+    <application>
+        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
+    </application>
+
+</manifest>
\ No newline at end of file
diff --git a/node_modules/react-native-code-push/android/app/src/main/AndroidManifest.xml b/node_modules/react-native-code-push/android/app/src/main/AndroidManifest.xml
index 5bd1596..9b2755f 100644
--- a/node_modules/react-native-code-push/android/app/src/main/AndroidManifest.xml
+++ b/node_modules/react-native-code-push/android/app/src/main/AndroidManifest.xml
@@ -3,8 +3,4 @@
 
     <uses-permission android:name="android.permission.INTERNET" />
 
-    <application>
-        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
-    </application>
-
 </manifest>

```

</details>

### CODE REVIEW

**Comment by floydkim** [comment]
@microsoft-github-policy-service agree

**Comment by DmitriyKirakosyan** [comment]
Hi @floydkim, merging this PR would mean you will be updating the `react-native-code-push` package to latest version once it is released. I would recommend trying to update it to the current latest version `8.2.2` and test if it works with your `react-native@0.67` project. Since version `0.67` is archived, I also recommend migrating to a newer React Native version if you haven't done so yet.

**Comment by floydkim** [comment]
hello! @DmitriyKirakosyan 
It's been about 10 months since I created this PR and the app I'm working on is now using react-native 0.73 with `react-native-code-push@8.2.2` based package.
If this PR is merged, I'd be happy to test the new release on the app.
Thank you.

**Comment by DmitriyKirakosyan** [comment]
Also related https://github.com/microsoft/react-native-code-push/issues/2658/

**Review by DordeDimitrijev — APPROVED** [review]

**Pull request merged**
