### PR TITLE
Remove link/unlink scripts & large dependencies

### PR DESCRIPTION
**Pull request by newyankeecodeshop**
The scripts for linking & unlinking the library using the old React Native package manager include three dependencies:
1. `inquirer`
2. `plist`
3. `semver`

Inquirer is a large dependency that takes up almost 24MB in a typical install. Since these scripts are no longer used with React Native 0.60+, they and their dependencies are no longer needed in this project. I removed the script files and updated `package.json`.

I verified the change by running all tests without incident.

### CODE REVIEW

**Comment by newyankeecodeshop** [comment]
Hi @alexandergoncharov do you have any feedback for this PR?

**Comment by alexandergoncharov** [comment]
Hi @newyankeecodeshop, 
Unfortunately, I'm no longer part of the CodePush team.

@doomkit , could you please take a look? :)

**Comment by newyankeecodeshop** [comment]
Happy 2022 @doomkit , can you review this PR for me?

**Comment by newyankeecodeshop** [comment]
Hi @doomkit , can this PR get a look? Thank you

**Comment by ls-andrew-goodale** [comment]
The React Native CLI has removed `link` and `unlink` commands via https://github.com/react-native-community/cli/pull/1537
Can @doomkit or someone please review or reject this PR?

**Pull request closed without merging**
