### PR TITLE
Split README.md into seperate setup and api docs

### PR DESCRIPTION
**Pull request by jeremistadler**
The README is becoming a bit crouded so I took the matter in hand 😄 

Any other layout ideas? 
Should we use the wiki instead? 
All feedback is welcome! 🌮

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by jeremistadler** [comment]
@geof90 @lostintangent @itsananderson 
Have any spare time for this? 😄

**Comment by panarasi** [comment]
Hey @jeremistadler Thanks for the Pull request. We were tied up with fixing 0.40 bugs - I think this looks good.

@silhouettes I want to merge this PR. Github also now allows gh-pages for the docs folder, so this could also help in automatically updating code-push docs.

**Comment by silhouettes** [comment]
@paranasi @jeremistadler - I've been meaning to go through this, I just wanted to figure out how the main website will reflect these changes (http://microsoft.github.io/code-push/docs/react-native.html), seeing as currently it's also a monolith, and yes it would be nice to have an auto-updating solution. Will give this some thought but also open to ideas! Tagging @buptkang also as this will be related to your work.

**Comment by jeremistadler** [comment]
@panarasi @silhouettes Thanks, I guess this PR will brake the site if merged as of now.

Considered other solutions such as gitbook or readthedocs?

**Comment by silhouettes** [comment]
Thanks for the tip, we'll check it out! @buptkang has agreed to look at this as part of his work to synchronize the website with the GitHub docs. I've assigned this to him, and he will likely need approximately one week as he just needs to finish what he's currently working on.

Thanks so much for this @jeremistadler, this is a very thoughtful and useful contribution. Please let us know if you'd like us to get this done sooner.

**Comment by buptkang** [comment]
I approved this document split PR. I have put the gulp script in the website repo to automatically synchronize the document change in this repo.

**Comment by silhouettes** [comment]
Thank you @jeremistadler :)

**Comment by silhouettes** [comment]
@buptkang - you might need to check if there have been any changes to the README since this PR was submitted, because they may not be reflected here

**Pull request merged**
