### PR TITLE
Bump minimum Windows SDK version to 10.0.17763.0

### PR DESCRIPTION
**Pull request by VMBindraban**
Fixes https://github.com/microsoft/react-native-code-push/issues/2624

### CODE REVIEW

**Comment by VMBindraban** [comment]
@AnatolyPristensky Can you rerun the rest?

**Comment by DmitriyKirakosyan** [comment]
@VMBindraban , are you still interested in this PR?

**Comment by VMBindraban** [comment]
We moved away from codepush a couple of weeks ago since it's being retired and there is no alternative setup yet. 
This PR is still required for people that use codepush with react-native-windows.

**Comment by DmitriyKirakosyan** [comment]
@VMBindraban, thanks for the update.

Did you test the changes when you prepared this PR? Do you remember why you removed the entire `<PropertyGroup Label="Configuration">` section? Was it not needed?

**Comment by VMBindraban** [comment]
I tested the changes at the time yes.

Regarding removal of the section, i don't remember why i removed it. I was using Visual studio 2022 at the time. (v143)
Visual Studio 2019 (V142) is now EOL.

**Comment by DmitriyKirakosyan** [comment]
https://github.com/microsoft/react-native-code-push/pull/2719 is merged. Closing this.
@VMBindraban thank you for the contribution!

**Pull request closed without merging**
