### PR TITLE
Remove jcenter

### PR DESCRIPTION
**Pull request by owjsub**
"Based on the current timeline, builds that use JCenter will be able to resolve dependencies until February 1, 2022 without changes. After that date, there are no guarantees that you will be able to build your software if you continue to use JCenter." --https://blog.gradle.org/jcenter-shutdown

https://github.com/microsoft/react-native-code-push/issues/2213

### CODE REVIEW

**Review by BogdanRad — APPROVED** [review]

**Comment by BogdanRad** [comment]
Can anyone merge this pr?

**Review by gabrielluka — APPROVED** [review]

**Comment by andresesfm** [comment]
This ticket should be closed after the PR ^^ was merged

**Comment by je7ov** [comment]
Anyone know when this will be merged in?

**Comment by pedpess** [comment]
@je7ov as a workaround you can use [patch-package](https://github.com/ds300/patch-package) to patch the fix yourself while this PR is not yet merged.

Here's the diff

```sh
 buildscript {
     repositories {
-        jcenter()
+        google()
+        mavenCentral()
     }
     dependencies {
         classpath 'com.android.tools.build:gradle:1.3.0'
@@ -15,6 +16,6 @@ buildscript {
 allprojects {
     repositories {
         mavenLocal()
-        jcenter()
+        mavenCentral()
     }
 }
```

**Comment by pedpess** [comment]
Change landed in 7.0.5, so I think this issue can be closed? @gabrielluka @BogdanRad 

https://github.com/microsoft/react-native-code-push/compare/v7.0.4...v7.0.5

**Comment by vTrip** [comment]
Please merge this. `v7.0.5` does not include this change

https://github.com/microsoft/react-native-code-push/blob/master/android/build.gradle#L5

https://github.com/microsoft/react-native-code-push/blob/master/android/build.gradle#L18

**Comment by huynhtastic** [comment]
Is there a timeline for adding this in? We'd really like to remove any dependencies on `jcenter` from our app.

**Review by huynhtastic — APPROVED** [review]
This is patched in our version of react-native-code-push and works fine

**Review by lucen-ms — APPROVED** [review]

**Review by lucen-ms — APPROVED** [review]

**Pull request merged**
