### PR TITLE
CodePush for React Native on Android 

### PR DESCRIPTION
**Pull request by geof90**
Currently, this doesn't support rollback after applying updates. It also doesnt contain any tests. I would like to get a code review for this first and merge before I work on those things.

I have added some installation documentation in the [README](https://github.com/Microsoft/react-native-code-push/tree/first-check-in-for-android#installation-android) for whoever wants to dogfood.

@lostintangent and everyone else

### CODE REVIEW

**Comment by ide** [comment]
Do you want to submit this upstream?

**Comment by geof90** [comment]
@ide In order to get this to work I had to write my own overriding classes (CodePushReactRootView.java, etc) to RN core modules in order to support to loading bundles from files paths instead of from the assets folder, because the new downloaded update packages need to be persisted somewhere in a user writable folder. I noticed there was another pull request that implements the same functionality. https://github.com/facebook/react-native/pull/2864 Is there any update on whether that would be merged soon? If that works, then CodePush can use that and thus stay as a RN extension plugin that doesn't modify RN core modules and thus does not need to be submitted upstream. Although yes, we would love to help out on the main RN project!

**Comment by ide** [comment]
#2864 will be merged soon. I hope we can include it with 0.14-rc or 0.15-rc. I'm a believer in making RN core be flexible and have small surface area so that projects like yours can integrate with it as plugins, and it's exciting to see your work.

**Comment by geof90** [comment]
@ide Cool! Looking forward to seeing that change being merged.

**Comment by geof90** [comment]
Closing, will send a new PR that doesn't use of the overridden facebook classes.

**Pull request closed without merging**
