### PR TITLE
add android ci

### PR DESCRIPTION
**Pull request by gengjiawen**
build log: https://circleci.com/gh/gengjiawen/react-native-code-push/5.

### CODE REVIEW

**Comment by yuri-kulikov** [comment]
Hi @gengjiawen,
Thanks for contributing!

Could you explain what these changes are and why they are needed?

**Comment by alexandergoncharov** [comment]
Could you please provide more detailed information about what is issue exactly and what is solution of this issue with fixing steps? As here isn't full information about changes at now.

**Comment by gengjiawen** [comment]
So have you got experience with Jenkins or Travis or azcure devops ?

**Comment by alexandergoncharov** [comment]
@gengjiawen ,Yeah, I have. :)
I just would like to ask you to place here full information in PR description for understanding what is going on without looking in code. It helps other guys understanding your changes if they will investigate code and go in git history and PRs.

You can set it with Issue field and Solution field. Thanks!

**Comment by alexandergoncharov** [comment]
Hi @gengjiawen 

I'm going to close this PR for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it by answering on question above and we will continue our work on this.

Thanks,
Alexander

**Pull request closed without merging**
