### PR TITLE
Codepush HOC should unmount app before restart

### PR DESCRIPTION
**Pull request by savv**
RN Apps currently don't get the opportunity to destruct themselves prior to a restart, leading to crashes and bugs:

https://github.com/microsoft/react-native-code-push/issues/2567#issuecomment-1820827232

This is an attempt to mitigate these crashes, by properly unmounting `<App />`.

I'm looking forward to your feedback

### CODE REVIEW

**Comment by savv** [comment]
@microsoft-github-policy-service agree

**Comment by savv** [comment]
ping?

**Comment by viniciusmoreria** [comment]
this is not missing the state in the class construtor?

```
      constructor() {
        super();
        this.state = { inactive: false };
      }
```

**Comment by velimir-jankovic** [comment]
@savv Thank you for this contribution! I'm a bit concerned that we may affect existing apps with this change.
I think it would be a good idea to put this change behind an option (for now), what do you think?

**Pull request closed without merging**
