### PR TITLE
add overloaded type for CodePush function that accepts a React Component

### PR DESCRIPTION
**Pull request by gwmccull**
per the documentation, the `codePush` function can be used in one of the following ways:
```
codePush(config)(App)
codePush(App)
```
The current types only support the former call signature. I added a type definition that supports the 2nd call signature

### CODE REVIEW

**Comment by gwmccull** [comment]
I chose to use `any` for the component type since that was what the current type definition uses and because the React types are not available in this repo

**Comment by alexandergoncharov** [comment]
Hi @gwmccull ,
Thanks for contributing!

Good catch!

**Comment by alexandergoncharov** [comment]
@gwmccull could you please merge the current Master into your branch?

**Comment by gwmccull** [comment]
@alexandergoncharov I merged master

**Pull request merged**
